name: AI 代码审查

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: AI 代码审查
        uses: J3n5en/bugment@main
        with:
          augment_access_token: ${{ secrets.AUGMENT_ACCESS_TOKEN }}
          augment_tenant_url: ${{ secrets.AUGMENT_TENANT_URL }}
